### ISSUE TITLE
nginx supports server push now

### ISSUE THREAD

**Issue by vdloo** [yireo/Yireo_LinkPreload#10]
> HTTP/2 Server Push doesn't work with Nginx and they have no plans in supporting this.

this is no longer true, see https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/

**Comment by jissereitsma** [comment]
Cool, thanks! I was waiting for that. I'll update the docs when I see a chance. Additionally the Nginx doc also mentions something that has been on my wishlist as well: Add a simple cookie check so that a Server Push only happens on the first request. Todo.
