### ISSUE TITLE
CE2.2.6 - Area code problems

### ISSUE THREAD

**Issue by gewaechshaus** [yireo/Yireo_LinkPreload#13]
Since 2.2.4 the area code needs to be set.

```
 [error] 8731#8731: *315067 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Magento\Framework\Exception\LocalizedException: Area code is not set in /var/www/html/vendor/magento/framework/App/State.php:152
Stack trace:
#0 /var/www/html/vendor/yireo/magento2-serverpush/Plugin/ResponsePlugin.php(76): Magento\Framework\App\State->getAreaCode()
#1 /var/www/html/vendor/yireo/magento2-serverpush/Plugin/ResponsePlugin.php(61): Yireo\ServerPush\Plugin\ResponsePlugin->shouldAddLinkHeader(Object(Magento\Framework\App\Response\Http\Interceptor))
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(121): Yireo\ServerPush\Plugin\ResponsePlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/html/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(26): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('" while reading response header from upstream ...
```

**Comment by jissereitsma** [comment]
Thanks for reporting this. Could you share a bit more detail? I have tested this in 2.2.4 and 2.2.6 in both the Developer Mode and the Production Mode and have not encountered this issue myself yet.

**Comment by gewaechshaus** [comment]
@jissereitsma - no problem, thank you for providing the module, We have to analyze this in detail. The thing is, it doesn't get logged on every request, it only appears every x minutes, so this might be related to a cronjob task or cache warm issue as a first guess.

Did you had varnish in front?

**Comment by jissereitsma** [comment]
I have not tested this with Varnish. However, please note that the issue is with the initialization of the area, which is not specific to Varnish at all. The area in the frontend is always `frontend`.

**Comment by gewaechshaus** [comment]
@jissereitsma - I have to take a deeper look, sorry. From my first readings I thought that the plugin is triggered on each request and this method should avoid adding the link header to other areas than frontend. Yes, that's clear to me (frontend area = frontend :))

**Comment by jissereitsma** [comment]
I think this can be closed then. Feel free to reopen if things are unclear.
