### ISSUE TITLE
Installation request for symfony/css-selector (locked at v4.2.1) -> satisfiable by symfony/css-selector[v4.2.1].

### ISSUE THREAD

**Issue by mdehaan** [yireo/Yireo_LinkPreload#17]
[u28883p36391@web0084 public_html]$ composer require yireo/magento2-serverpush
Using version ^0.0.7 for yireo/magento2-serverpush
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yireo/magento2-serverpush ^0.0.7 -> satisfiable by yireo/magento2-serverpush[0.0.7].
    - Conclusion: remove symfony/css-selector v4.2.1
    - Conclusion: don't install symfony/css-selector v4.2.1
    - yireo/magento2-serverpush 0.0.7 requires symfony/css-selector ^2.7|^3.0 -> satisfiable by symfony/css-selector[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2.7.49, v2.7.5, v2.7.50, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/css-selector[v2.7.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.11, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.12, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.13, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.14, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.15, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.16, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.17, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.18, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.19, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.20, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.21, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.22, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.23, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.24, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.25, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.26, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.27, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.28, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.29, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.30, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.31, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.32, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.33, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.34, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.35, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.36, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.37, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.38, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.39, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.40, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.41, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.42, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.43, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.44, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.45, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.46, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.47, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.48, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.49, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.50, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.7.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.11, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.12, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.13, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.14, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.15, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.16, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.17, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.18, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.19, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.20, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.21, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.22, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.23, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.24, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.25, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.26, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.27, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.28, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.29, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.30, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.31, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.32, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.33, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.34, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.35, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.36, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.37, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.38, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.39, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.40, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.41, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.42, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.43, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.44, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.45, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.46, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.47, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.48, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.49, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v2.8.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.0.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.1.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.11, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.12, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.13, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.14, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.2.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.11, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.12, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.13, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.14, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.15, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.16, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.17, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.18, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.3.9, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.0, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.1, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.10, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.11, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.12, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.13, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.14, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.15, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.16, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.17, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.18, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.19, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.2, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.20, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.3, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.4, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.5, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.6, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.7, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.8, v4.2.1].
    - Can only install one of: symfony/css-selector[v3.4.9, v4.2.1].
    - Installation request for symfony/css-selector (locked at v4.2.1) -> satisfiable by symfony/css-selector[v4.2.1].

**Comment by jissereitsma** [comment]
Which Magento version?

**Comment by mdehaan** [comment]
Magento 2.2.7

Op wo 19 dec. 2018 om 09:07 schreef Jisse Reitsma <notifications@github.com

**Comment by jissereitsma** [comment]
Thanks. Sorry for the delay. I was now able to confirm the issue under 2.2.7. There is now a version 0.0.8 out of this module to embrace the new Symfony packages (included in Magento) as well.

**Comment by mdehaan** [comment]
Thanks for fixing the issue :)

Op 28 dec. 2018 23:13 schreef "Jisse Reitsma" <notifications@github.com>:

Closed #17 <https://github.com/yireo/Yireo_ServerPush/issues/17>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yireo/Yireo_ServerPush/issues/17#event-2047767789>, or mute
the thread
