### ISSUE TITLE
nginx server push and absolute URLs in 1.4.1 update

### ISSUE THREAD

**Issue by fsw** [yireo/Yireo_LinkPreload#21]
Hello,

Seems that `nginx` `http2_push_preload` option ignores absolute URLs in `Link` header. I guess it makes sense as there is a higher chance those resources should be served by same host.

Previously links like "http://mysite.com/style.css" were changed to "/style.css" in https://github.com/yireo/Yireo_LinkPreload/blob/9d0bef264d7f3c45c6508c8e5ef210cfd14adcfb/Plugin/ResponsePlugin.php#L270 and everything was working fine.

Commit f850d6eea3559d647eb4ca17ef429c6ab04d48b8 in 1.4.1 changed this and now this stopped working.

I would fix it by reverting this commit but I am not sure why HTTP/HTTPS URLs should be prevented to turning into static content URLs. At the moment this function seems to be in wrong order as absolute URLs will never get to be checked if they match store base URL.

cheers.

**Comment by jissereitsma** [comment]
Good point. The following commit fixes this by simply trying to turn a full URL into an absolute URL: https://github.com/yireo/Yireo_LinkPreload/commit/e09e9f958850a78971f3ea81465be6a731ed9eff Release 1.4.2 ships with this fix.
