### ISSUE TITLE
Adds wrong files when merging

### ISSUE THREAD

**Issue by barryvdh** [yireo/Yireo_LinkPreload#3]
When mergin files is enabled, it still adds the old files. Would you recommend turning of merging the js/css in favor of http push, or is that a bug?

**Comment by jissereitsma** [comment]
No, this would be a bug. The extension simply should attempt to add the `Link` header where possible, regardless of what files are available. I would not recommend anything regarding merging on/off with/without HTTP/2 server push on/off - I would actually encourage everybody to benchmark.

**Comment by barryvdh** [comment]
Ok, well it can be fixed with #4 and added a note in #5
