### ISSUE TITLE
Issue after upgrade to version 1.4.11 ArgumentCountError Yireo\LinkPreload\Link\LinkParser::addLink()

### ISSUE THREAD

**Issue by chrisastley** [yireo/Yireo_LinkPreload#31]
Hi, 

Just installed on a new site build I'm doing and got this error;

[2021-07-08 15:16:13] main.CRITICAL: ArgumentCountError: Too few arguments to function Yireo\LinkPreload\Link\LinkParser::addLink(), 2 passed in /var/www/vhosts/domain.com/htdocs_m2/vendor/yireo/magento2-linkpreload/Link/LinkParser.php on line 220 and exactly 3 expected in /var/www/vhosts/domain.com/htdocs_m2/vendor/yireo/magento2-linkpreload/Link/LinkParser.php:188
Stack trace:
#0 /var/www/vhosts/domain.com/htdocs_m2/vendor/yireo/magento2-linkpreload/Link/LinkParser.php(220): Yireo\LinkPreload\Link\LinkParser->addLink('https://tribute...', 'script')
#1 /var/www/vhosts/domain.com/htdocs_m2/vendor/yireo/magento2-linkpreload/Link/LinkParser.php(72): Yireo\LinkPreload\Link\LinkParser->addLinkHeadersFromLayout()
#2 /var/www/vhosts/domain.com/htdocs_m2/vendor/yireo/magento2-linkpreload/Plugin/ResponsePlugin.php(75): Yireo\LinkPreload\Link\LinkParser->parse(Object(Magento\Framework\App\Response\Http\Interceptor))
#3 /var/www/vhosts/domain.com/htdocs_m2/vendor/magento/framework/Interception/Interceptor.php(121): Yireo\LinkPreload\Plugin\ResponsePlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#4 /var/www/vhosts/domain.com/htdocs_m2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/vhosts/domain.com/htdocs_m2/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(23): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#6 /var/www/vhosts/domain.com/htdocs_m2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Response\Http\Interceptor->sendResponse()
#7 /var/www/vhosts/domain.com/htdocs_m2/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#8 {main} [] []

I've temporarily rolled back to 1.4.10 which no issue.

Problem is the call to addLink on line 220 of vendor/yireo/magento2-linkpreload/Link/LinkParser.php has only 2 parameters.

**Comment by jissereitsma** [comment]
Thanks for addressing this. I'm not sure why I overlooked this in the release of yesterday - it worked fine on my end. But now on a different environment I get the same issue. Version 1.4.12 is now out and should fix this.

**Comment by chrisastley** [comment]
Thanks for the quick fix.
