### ISSUE TITLE
Link preload is rendered not only in the head tag

### ISSUE THREAD

**Issue by MaximGns** [yireo/Yireo_LinkPreload#32]
We are using current module in our project. But encountered that it adds instead of 2 preload links to page, more than 90 of them. After some more investigation. We saw that we loaded svg with a title (<svg> ... <title> Title of svg </title> </svg>).

After some investigation it seems that it is doing a string replace of all titles in the body instead of the first title of the page (in the head tag)

To test, I have replaced following lines:

**from:**
$body = str_replace('</title>', "</title>\n" . implode("\n", $newTags), $body);

**To:**
$body = preg_replace('^</title>^',"</title>\n" . implode("\n", $newTags) , $body, 1);

Result:
2 elements found with preload instead of 90+

**Comment by jissereitsma** [comment]
Thanks for spotting this. I've now released version 1.4.13 with this fix. 

Please note that this was actually ideal to create a GitHub PR for: Open up the file, edit the code, submit the form and there you have a PR. It probably would have taken less time than to copy the lines of code here. Just an idea for the future.

Thanks again.

**Comment by MaximGns** [comment]
@jissereitsma indeed good remark 😆
