### ISSUE TITLE
Link in headers can lead to page not loading

### ISSUE THREAD

**Issue by Quazz** [yireo/Yireo_LinkPreload#35]
When you have loads and loads of links to be preloaded on a page, this can lead to the page not loading due to it hitting "header size" limits (will say something about premature end to script in PHP error logs)

This can occur on a page by page basis.

Possible solutions:

- Config option to disable links in header globally (links in head work fine after all)
- Artificially limit the amount of links added to headers (though this could still lead the problems since it's not the only headers around, that said the upper limit on most webservers is 8KB in total)
- Disable headers full stop (since performance difference is neglible and it's pointless to have both on at the same time)
- Add a way to exclude certain links from preload (eg if they are marked as lazy loading, this one should probably be done regardless for images)

Relevant function:

https://github.com/yireo/Yireo_LinkPreload/blob/563c99e1b17c6659d0daa87c133397bf68bb07a8/Link/LinkParser.php#L81

**Comment by jissereitsma** [comment]
Thanks for the PR. Fix is included in https://github.com/yireo/Yireo_LinkPreload/blob/master/CHANGELOG.md
