### ISSUE TITLE
no file resource refrenced just blank "rel=preload; as=style"

### ISSUE THREAD

**Issue by EmilyPepperman** [yireo/Yireo_LinkPreload#6]
Link => ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=style, ; rel=preload; as=script, ; rel=preload; as=script, ; rel=preload; as=script, ; rel=preload; as=script, ; rel=preload; as=script, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image, ; rel=preload; as=image

**Comment by jissereitsma** [comment]
Could you add some more details? Which Magento 2 version, which environment (webserver, HTTP/2 configuration, PHP version) and where this problem pops up exactly?

**Comment by EmilyPepperman** [comment]
Magento 2.1.7 CE
CentOS release 6.9 (Final)
Server version: Apache/2.4.25 (Unix)
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64)
PHP 7.0.19

I installed the extension on our website https://www.divegearexpress.com ... didn't' quite know how to see if it was working or not. Found a 
header checker: http://www.webconfs.com/http-header-check.php

See that our headers don't seem to reference any files in the Link

**Comment by jissereitsma** [comment]
Thanks. A few more questions: Is this in Production Mode or Developer Mode? And did you enable any of the JavaScript merging / bundling settings?

**Comment by jissereitsma** [comment]
I just checked your site. It also seems that somebody installed another module to move JavaScript to the bottom of the page and optimize things through lazy loading. This explains things. That other extension would need to be modified for `Link` headers to be sent properly. You have run into a conflict, that needs to be inspected first.

**Comment by EmilyPepperman** [comment]
Thank you for responding and helping. :-) Yes we are in production mode and using some deferjs tools to get the performance of M2 faster... which did work! We were also about to turn on minify to see if that would help more.

**Comment by EmilyPepperman** [comment]
We don't see why it would clash with what we are doing to defer JavaScript the extension can't extract CSS hrefs not JS src correct?

**Comment by jissereitsma** [comment]
Theoretically everything could work. However, it either means that the other extension requires heavy refactoring or that this extension needs heavy refactoring, only because this clash requires so. You have not yet mentioned which extension would cause the clash, so I guess some developer needs to be in the lead here to make sure this works on your shop. Unfortunately, I can't volunteer for that. I already helped people with creating the extension.

**Comment by EmilyPepperman** [comment]
Hi @jissereitsma  ... We are using this DeferJS extension on our website https://www.goivvy.com/blog/free-download-magento-2-defer-javascript-extension built by @goivvy

**Comment by EmilyPepperman** [comment]
@jissereitsma After all this I think it might be working on our site after all. The header test I used might be looking at only HTTP/1 requests and not HTTP/2 So that blank "noise" I posted above shows then. Can you look at our site and see if it looks like this is working fine? :-) https://www.divegearexpress.com THank you!
