### ISSUE TITLE
Font files...

### ISSUE THREAD

**Issue by n2diving-net** [yireo/Yireo_LinkPreload#9]
Doesn't appear to detect fonts, which would seem to be a great candidate for server push.... in particular we are using woff2 fonts...   content-type: application/font-woff2

**Comment by yireo** [comment]
How are the font files added to your HTML document then? Through XML layout?

**Comment by n2diving-net** [comment]
Currently using css @font-face to load the fonts.

**Comment by yireo** [comment]
I don't think that there is another technique than CSS to load fonts. So what you meant is something that can not be decided through the HTML document in the first place. Unfortunately, it makes it impossible to create. The only thing that could be done is create custom code to do this, based on the custom files that are going to be loaded. Unfortunately we can't include that in a standard extension.
